### ISSUE TITLE
"Invalid theme schema." on element desktop nightly

### ISSUE THREAD

**Issue by m3t4f1v3** [catppuccin/element#1]
Attempting to place the url in "Custom theme URL" does not work. Attempting to place the config.json in ~/.config/Element-Nightly also does not work

**Comment by ghostx31** [comment]
1530666843aeecea51248f2c893997727b685fef should fix the invalid scheme error. Please go through the README again for the updated steps. 

As for the `config.json` not working, Element-nightly does not push any sort of error in the debug logs. It seems to have to do something with the change in installation location [source: [here](https://aur.archlinux.org/packages/element-desktop-nightly-bin#comment-878340)] from `/opt/Element-nightly/` to `/opt/Element/`. I can get to this once again the AUR package has been updated.
