### ISSUE TITLE
Syntax higlighting

### ISSUE THREAD

**Issue by Nekosis** [catppuccin/element#3]
There's no syntax highlighting for code blocks:
![2023-09-28_22-23](https://github.com/catppuccin/element/assets/37462865/85ef4090-cfe3-430c-869e-7cd226fba808)
As opposed to the stock dark theme:
![2023-09-28_22-24](https://github.com/catppuccin/element/assets/37462865/85da7cf9-b352-439e-b83e-a8576c4c4bfa)

**Comment by ghostx31** [comment]
None of the custom themes that I have tried have syntax highlighting. It seems to be only possible in the default theme and Element has not described a way or has provided a token to enable syntax highlighting for custom themes, sadly. 
There is nothing I can do about this. 

If you find some custom theme which supports synrax highlighting, please let me know too.
